//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShelfProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Page { get; set; }
        public string Author { get; set; }
        public Nullable<int> Category { get; set; }

        public string CategoryName { get; set; }


        public virtual Category Category1 { get; set; }
    }
}
